# Generated by Django 5.2.10 on 2026-03-10 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useractiontoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gdpr_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='gdpr_consent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
