# Generated by Django 5.2.10 on 2026-01-28 15:59

import django.contrib.postgres.fields
import django.db.models.deletion
import parler.fields
import parler.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, help_text='Slugified version of the English name, auto-generated', max_length=255, unique=True)),
                ('practice_zone', models.CharField(choices=[('everywhere', 'Everywhere'), ('climbing_gym', 'Climbing Gym')], default='everywhere', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='exercises/images/')),
                ('gif', models.FileField(blank=True, null=True, upload_to='exercises/gifs/')),
                ('video', models.URLField(blank=True, null=True)),
                ('resolution', models.CharField(choices=[('repetition', 'Repetition'), ('duration', 'Duration')], default='repetition', help_text='Does this exercise count by repetitions or seconds?', max_length=20)),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, help_text='Slugified version of the English name, auto-generated', max_length=255, unique=True)),
                ('focus', models.CharField(choices=[('general_fitness', 'General Fitness'), ('climbing_performance', 'Climbing Performance')], default='general_fitness', max_length=20)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('duration_days', models.PositiveIntegerField(default=14, help_text='Duration of program in days')),
                ('is_public', models.BooleanField(default=False)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('focus_axes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('technical_bouldering', 'Technical bouldering'), ('project_bouldering', 'Project bouldering'), ('route_technique', 'Route technique'), ('movement_quality', 'Movement quality'), ('coordination', 'Coordination'), ('footwork', 'Footwork'), ('power', 'Power'), ('max_strength', 'Max strength'), ('power_endurance', 'Power endurance'), ('endurance_continuity', 'Endurance / continuity'), ('climbing_volume', 'Climbing volume'), ('finger_strength', 'Finger strength'), ('upper_body_strength', 'Upper body strength'), ('core_tension', 'Core tension'), ('lock_off_strength', 'Lock-off strength'), ('pulling_strength', 'Pulling strength'), ('general_strength', 'General strength'), ('mobility', 'Mobility'), ('stability', 'Stability'), ('balance', 'Balance'), ('conditioning', 'Conditioning'), ('active_recovery', 'Active recovery'), ('injury_prevention', 'Injury prevention'), ('antagonist_training', 'Antagonist training'), ('progressive_overload', 'Progressive overload'), ('deload', 'Deload / recovery'), ('movement_efficiency', 'Movement efficiency')], max_length=50), blank=True, default=list, size=None)),
                ('cycle_rhythm', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ExerciseTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='programs.exercise')),
            ],
            options={
                'verbose_name': 'exercise Translation',
                'db_table': 'programs_exercise_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProgramTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('realistic_if', models.JSONField(blank=True, default=list)),
                ('not_realistic_if', models.JSONField(blank=True, default=list)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='programs.program')),
            ],
            options={
                'verbose_name': 'program Translation',
                'db_table': 'programs_program_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
