# Generated by Django 5.2.10 on 2026-01-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='practice_zone',
            field=models.CharField(choices=[('everywhere', 'Everywhere'), ('climbing_gym', 'Climbing Gym')], db_index=True, default='everywhere', max_length=20),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='resolution',
            field=models.CharField(choices=[('repetition', 'Repetition'), ('duration', 'Duration')], db_index=True, default='repetition', help_text='Does this exercise count by repetitions or seconds?', max_length=20),
        ),
        migrations.AlterField(
            model_name='program',
            name='focus',
            field=models.CharField(choices=[('general_fitness', 'General fitness'), ('climbing_performance', 'Climbing performance')], db_index=True, default='general_fitness', max_length=32),
        ),
        migrations.AlterField(
            model_name='program',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], db_index=True, default='intermediate', max_length=32),
        ),
    ]
