# Generated by Django 5.2.10 on 2026-02-03 00:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0002_alter_exercise_practice_zone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgram',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], db_index=True, default='active', max_length=32)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_programs', to='programs.program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProgramFeedback',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usefulness', models.CharField(blank=True, choices=[('not_useful', 'Not Useful'), ('useful', 'Useful'), ('very_useful', 'Very Useful')], db_index=True, max_length=32, null=True)),
                ('would_repeat', models.BooleanField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('user_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='tracking.userprogram')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProgramSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cycle_count', models.PositiveIntegerField()),
                ('session_in_cycle', models.PositiveIntegerField()),
                ('session_snapshot', models.JSONField()),
                ('rating', models.CharField(blank=True, choices=[('too_easy', 'Too Easy'), ('ok', 'OK'), ('too_hard', 'Too Hard')], db_index=True, max_length=32, null=True)),
                ('user_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tracking.userprogram')),
            ],
            options={
                'ordering': ['user_program', 'cycle_count', 'session_in_cycle'],
                'unique_together': {('user_program', 'cycle_count', 'session_in_cycle')},
            },
        ),
    ]
